version: '3.8'

services:
  frontend:
    build:
      context: ./gestionRhFront
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend  

  backend:
    build:
      context: ./gestionRhBack
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    build:
      context: ./data
      dockerfile: Dockerfile
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
